Repository KmSTeam3/MyCargonaut, pull requests merged in 2020-06, with the labels that each got.

#22 Added profile page with functionality to update profile and logout
  src/app/app-routing.module.ts
  src/app/profile/profile-routing.module.ts
  src/app/profile/profile.module.ts
  src/app/profile/profile.page.html
  src/app/profile/profile.page.scss
  src/app/profile/profile.page.spec.ts
  src/app/profile/profile.page.ts
  src/app/shared/user.service.ts
Labels: Sprint2

#24 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#30 12 manage vehicle 2
  src/app/manage-vehicle/e-modal/e-modal-routing.module.ts
  src/app/manage-vehicle/e-modal/e-modal.module.ts
  src/app/manage-vehicle/e-modal/e-modal.page.html
  src/app/manage-vehicle/e-modal/e-modal.page.scss
  src/app/manage-vehicle/e-modal/e-modal.page.spec.ts
  src/app/manage-vehicle/e-modal/e-modal.page.ts
  src/app/manage-vehicle/edit-vehicle/edit-vehicle.page.ts
  src/app/manage-vehicle/manage-vehicle-routing.module.ts
  src/app/manage-vehicle/manage-vehicle.page.spec.ts
Labels: Sprint3

#31 27 impressum
  src/app/app-routing.module.ts
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/impressum/impressum-routing.module.ts
  src/app/impressum/impressum.module.ts
  src/app/impressum/impressum.page.html
  src/app/impressum/impressum.page.scss
  src/app/impressum/impressum.page.spec.ts
  src/app/impressum/impressum.page.ts
  src/app/manage-vehicle/manage-vehicle.page.html
  src/app/manage-vehicle/manage-vehicle.page.ts
  src/app/profile/profile.page.html
  src/app/profile/profile.page.ts
  src/app/route-search/route-search.page.html
  src/app/route-search/route-search.page.scss
  src/app/route-search/route-search.page.ts
  src/app/search-result/search-result.page.html
  src/app/search-result/search-result.page.ts
  src/app/transport-search/transport-search.page.html
  src/app/transport-search/transport-search.page.ts
Labels: Sprint3

#32 #14 payment
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/manage-vehicle/modal/modal.page.ts
  src/app/payment-choice/payment-choice-routing.module.ts
  src/app/payment-choice/payment-choice.module.ts
  src/app/payment-choice/payment-choice.page.html
  src/app/payment-choice/payment-choice.page.scss
  src/app/payment-choice/payment-choice.page.spec.ts
  src/app/payment-choice/payment-choice.page.ts
  src/app/payment-detail/payment-detail.module.ts
  src/app/payment-detail/payment-detail.page.html
  src/app/payment-detail/payment-detail.page.scss
  src/app/payment-detail/payment-detail.page.ts
  src/app/search-result/list-result/list-result.page.html
  src/app/search-result/list-result/list-result.page.scss
  src/app/search-result/list-result/list-result.page.ts
  src/app/search-result/search-result.module.ts
  src/app/search-result/search-result.page.ts
  src/app/shared/payment
  src/assets/PayPal-Logo.png
  src/global.scss
Labels: Sprint3

#33 Delivery
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/delivery/delivery-list/delivery-list-routing.module.ts
  src/app/delivery/delivery-list/delivery-list.module.ts
  src/app/delivery/delivery-list/delivery-list.page.html
  src/app/delivery/delivery-list/delivery-list.page.scss
  src/app/delivery/delivery-list/delivery-list.page.spec.ts
  src/app/delivery/delivery-list/delivery-list.page.ts
  src/app/delivery/delivery-routing.module.ts
  src/app/delivery/delivery.module.ts
  src/app/delivery/delivery.page.html
  src/app/delivery/delivery.page.scss
  src/app/delivery/delivery.page.spec.ts
  src/app/delivery/delivery.page.ts
  src/app/delivery/modal-delivery/modal-delivery-routing.module.ts
  src/app/delivery/modal-delivery/modal-delivery.module.ts
  src/app/delivery/modal-delivery/modal-delivery.page.html
  src/app/delivery/modal-delivery/modal-delivery.page.scss
  src/app/delivery/modal-delivery/modal-delivery.page.spec.ts
  src/app/delivery/modal-delivery/modal-delivery.page.ts
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/manage-vehicle/add-vehicle/add-vehicle.page.ts
  src/app/manage-vehicle/manage-vehicle.page.ts
  src/app/route-search/route-search.page.html
  src/app/route-search/route-search.page.ts
  src/app/search-result/search-result.page.ts
  src/app/shared/data-helper.service.spec.ts
  src/app/shared/data-helper.service.ts
  src/app/shared/shipment.service.spec.ts
  src/app/shared/shipment.service.ts
  src/app/shared/shipment.ts
  src/app/shared/user.service.ts
  src/assets/icon/Logo.jpg
  src/index.html
Labels: Fix, Sprint3

#37 Add bugfixes to dev branch from #36 documentation branch
  src/app/delivery/delivery.page.ts
  src/app/delivery/modal-delivery/modal-delivery.page.ts
  src/app/home/home.module.ts
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/menu-header/menu-header.page.ts
  src/app/payment-choice/payment-choice.page.html
  src/app/payment-choice/payment-choice.page.ts
  src/app/payment-detail/payment-detail.page.html
  src/app/payment-detail/payment-detail.page.ts
  src/app/register/register.page.ts
  src/app/route-search/route-search.page.ts
  src/app/search-result/list-result/list-result.page.html
  src/app/transport-search/transport-search.module.ts
  src/app/transport-search/transport-search.page.html
  src/app/transport-search/transport-search.page.ts
Labels: Fix, Sprint3, documentation
